### ISSUE TITLE
Adjust nav bar media queries

### ISSUE THREAD

**Issue by Kaskade01** [marcnormandin/personal_website#2]
Because you have so many navigation bar links, the nav bar collapses to a second row as you shrink the window.

The media queries that handle this need to be adjusted.

**Comment by Kaskade01** [comment]
Alternatively, you can consolidate the navigation bar links so you don't have so many.

**Comment by marcnormandin** [comment]
I don't know what you mean by 'media queries'. Can you please explain?

I can adjust the nav-bar I think.

**Comment by marcnormandin** [comment]
A second dropdown menu was added to the navbar to clear up space.

Issue resolved.
